### ISSUE TITLE
Adjudicator Design Document

### ISSUE THREAD

**Issue by irobert4** [c-to-the-fazzy/cardiathena#10]
Adjudicator
# Description

The adjudicator design document needs to be cleaned up, and coding should begin soon on the adjudicator as well.

# Tasks

- [x] Clean up document
  - [x] Game Logic - What needs to stay, removed, or modified
  - [x] Score - move into state, so remove 
  - [x] Masking Technique - remove or modify masking technique. Already coded.
  - [x] Adjudicator Class Structure - A lot of repeated info from the game logic section.
  - [x] Fix formatting to be consistent with all wiki documents.
- [x] Create pseudo-code for all functions in adjudicator
  - [x] start_game()
  - [x] step_game(action: Action)
  - [x] get_state()
  - [x] is_finished()
  - [x] agent_turn()

**Comment by msomarri** [comment]
Maybe we can eliminate the Game Logic section since everything on there exist in Adjudicator Class Structure. We can also modify the Game Logic section to describe a high-level idea of how the game will play out.
