### ISSUE TITLE
Build Up Project

### ISSUE THREAD

**Issue by irobert4** [c-to-the-fazzy/cardiathena#11]
# Description

Use the design documents to perfect the project. This should come after the creation of the prototype adjudicator.

# Tasks

- [ ]  Card-Counting Agent
  - [ ] get_action(partial_state : State)
- [ ]  Learning Agent
  - [ ] get_action(partial_state : State)
- [ ] Game Manager
  - [ ] Save game to database
- [ ] Database Python Script (i.e. how is data organized in database)

# Additional milestones

Completed Base Agent
Completed Random Agent
Completed Card-Counting Agent
Completed Game Manager
