### ISSUE TITLE
Create Adjudicator Prototype

### ISSUE THREAD

**Issue by aphelps4** [c-to-the-fazzy/cardiathena#13]
# Description

Create a prototype adjudicator that will be built upon. This prototype should be capable of playing a hearts game using random agents.

# Tasks

- [x] Adjudicator
   - [x] start_game()
   - [x] step_game(action: Action)
   - [x] get_state()
   - [x] is_finished()
   - [x] agent_turn()
- [x]  Base Agent
  - [x] get_action(partial_state : State)
- [x]  Random Agent
  - [x] get_action(partial_state : State)
- [x] Game Manager
  - [x] player_list
  - [x] adjudicator
  - [x] state_history
  - [x] action_history
  - [x] save_game

**Comment by davidjha** [comment]
So the latest commits to the prototype branch include fixing the agent_turn() from round robin to what its actually suppose to do.  Which is the trick winner leads the next trick, and goes around from there. 

Michael is working on showing the legal moves to the agents by masking every illegal move. So for example, if clubs is leading the trick and the current agent has a club, the partial state shown to the agent will not include anything other than playable club cards. At least that's what I think he has in mind. He is also working on check if legal move function in the adjudicator.

I'm working on the passing of the cards at the start of the rounds.

A adjudicator test file is up, we probably should write more tests.

**Comment by irobert4** [comment]
A quick note for Michael: Keep in mind that if the agent cannot follow suit then to my understanding an agent can pick whatever card they want (given that it belongs to them).

If you want some help, @ me on slack or text me. I will be able to get to it in the late evening.
