### ISSUE TITLE
Carlo's Git Example Issue

### ISSUE THREAD

**Issue by c-to-the-fazzy** [c-to-the-fazzy/cardiathena#21]
# Description

Some example description.

# Tasks

* [x] create this issue
* [x] make a branch
* [x] edit some code
* [x] create a pull request
