### ISSUE TITLE
Angela's Issue Example

### ISSUE THREAD

**Issue by aphelps4** [c-to-the-fazzy/cardiathena#24]
# Description

Describe here the major task you need to complete, make sure to note dependencies on other tasks. 

# Tasks

* [x] create this issue
* [x] make a branch
* [x] edit some code
* [x] create a pull request
