### ISSUE TITLE
Clean Up Adjudicator Prototype

### ISSUE THREAD

**Issue by irobert4** [c-to-the-fazzy/cardiathena#30]
# Description

The HeartsAdjudicator prototype has been finished but code clean up is still required.  The HeartsState class only needs to track deck of cards and their location and the score. The HeartsAdjudicator class needs to apply the hearts rules on any arbitrary HeartsAction and HeartsState and produce an update to the HeartsState. 

# Tasks

- [x] Move HeartState methods to HeartsAdjudicator
  - [x] current_player 
    - could use player hands for this. Whoever has the highest number of cards is the current player
  - [x] trick_number 
    - how? 
    - Count number of cards that have already been played and divide them by four
  - [x] trick_winner 
     - how? Might it be better to keep the trick_winner and trick_number as variables?
     - This keeps track of the current trick winner based on who has played so it will find all the cards currently in play (21-24) and choose the highest value in the current suit to find the winner
     - [x] trick_leader
         - Useful for finding the suit for players to follow
         - Look at all the players who have currently played and use that to infer who played first
  - [x] cards_of_trick needs to be inferred via a function call in the adjudicator
     - how?
- [x] Remove HeartsAdjudicator properties dependent on HeartsState 
  - Is step_game's "HeartsAction" parameter still required? Not sure how this works with the whole "adjudicator takes a state and returns a state" idea.
- [x] Merge the "Clean Up Adjudicator Prototype" branch with the "Create Adjudicator Prototype" branches when done. Then merge with master.

**Comment by kruzaavn** [comment]
my thoughts on how

according to `state.py` these are the encodings we're using

```python 
player_hand = [1, 2, 3, 4] # these encode the cards in the players hands
player_won = [11, 12, 13, 14] # these encode the cards won by a player
player_current = [21, 22, 23, 24] # these encode the cards the players have in the current trick
```

and HeartsState.values is a numpy array an has an ordered encoding by taking the product of 

```
cards = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
suits = ['C', 'D', 'S', 'H']
```

so that `HeartsState.values[0]` is the two of clubs `HeartsState.values[1]` is the three of clubs and so on

### current player and trick leader

play occurs clockwise. if we were to imagine that the players will always be oriented likewise 
![PlayOrder](https://user-images.githubusercontent.com/7274055/72209739-a90e5080-347f-11ea-9678-4a603927feb0.png)

we could use this structure to determine the lead player and current player from which elements of the `player_current` exist in the `HeartStates.values` array. 

e.g. if 22 and 23 are in `HeartStates.values` but 24 and 21 are not then player 2 lead and player 4 is the current player. 

be aware we can only do this before all four values have been filled in. meaning if all 4 are in the array we lose the information about who went first.

### Lead Suit

because the HearState.values order matters we look up who is the leader was from the function we just wrote and find the index of their played card in `HeartsState.values` and divide that index by 13 and use `int` of that number to index the cards array. 

### Tricks played

take the length of the `HeartsState.values[HeartsState.values> 10 and  HeartsState.values< 20]` and divide by 4

### cards of trick

we have already encoded this in `player_current`

**Comment by kruzaavn** [comment]
We could also extend the encoding so that [31, 32, 33, 34] indicate that that player led the trick with in which it's positioned.

**Comment by irobert4** [comment]
Personally I would prefer to extend the encoding for the trick leader using the values 31 to 34, but we'll have to see what the rest of the team thinks.

For the current player, in the example you gave would player 4 be the current player based on that structure? How exactly would that map to the state?  For example player 3 could have played 7C while player 2 played 3D.  Does that mean we need to loop twice through the state just to find who the current player is?

**Comment by kruzaavn** [comment]
No, if i were to do `HeartsState.values[HeartsState.values>20]` i would get a numpy array back that is [22, 23] according to the example above. Then  you parse the current player from that smaller array.

**Comment by irobert4** [comment]
Oh.  Is that bit of code specific to numpy arrays or is it built in python functionality for any array?

**Comment by kruzaavn** [comment]
That's [numpy.](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html) If you guys get a chance i'd look at some of the underlying machinery.

**Comment by c-to-the-fazzy** [comment]
I personally think numpy is overkill for this.  We are doing no numerical computations, only basic list manipulations.
