### ISSUE TITLE
Distributed-Computing/Database Research

### ISSUE THREAD

**Issue by davidjha** [c-to-the-fazzy/cardiathena#31]
# Description

In order to complete the research task of using argo for this project, here are some of things that need to be completed. Documentation on how to run a mysql singularity container on Argo will be posted on the wiki. Also we need to be sure agents will be able to pull data from the database, and update to the database. This probably needs to be tested with multiple agents accessing the database in bulk. With our prototype adjudicator, we can run games on Argo and start generating data to a database. This will also lead to a working SQL server prototype.

# Tasks

- [x] Documentation
  - [x] Write instructions on how to run mysql container on argo to the Wiki
- [x] Write test database code
  - [x]  Create test state database
  - [x]  Read data from test database
  - [x]  Write data to test database
- [x] Run code and many games on Argo
  - [x] Write slurm script
