### ISSUE TITLE
Cleanup-Adjudicator-Functionize-Stepgame

### ISSUE THREAD

**Issue by irobert4** [c-to-the-fazzy/cardiathena#35]
# Description

The adjudicator function stepgame() is a large function whose inner contents should be split into separate functions for better readability.

# Tasks

- [x] Annotate code with comments indicating which parts of stepgame() to split into separate functions
  - [x] Run these annotations by the whole group
- [x] Code the functionization
- [x] Merge to Adjudicator Cleanup Branch
