### ISSUE TITLE
Cleanup-Adjudicator-Functionize-AgentTurn

### ISSUE THREAD

**Issue by davidjha** [c-to-the-fazzy/cardiathena#36]
# Description

Lets try to make agent_turn() more readable. This will simplify the integration of our state minimization functions, and make the entire process more manageable.

# Tasks
- [x] Annotate code with comments indicating which parts of agent_turn() to split into separate functions
  - [x] Run these annotations by the whole group
- [x] Code the functionization
- [ ] Merge to Adjudicator Cleanup Branch
