### ISSUE TITLE
Simultaneous pass

### ISSUE THREAD

**Issue by msomarri** [c-to-the-fazzy/cardiathena#39]
Currently, the adjudicator handles passing by a sequential order. The goal is to create a simultaneous pass order. We don't have a roadmap on to accomplish this goal but any suggestion and ideas are welcome.

# Tasks

- [x] Brainstorm ideas on how to handle simultaneous pass 
  - [x] Have agent_turn return lists of needed information rather than focusing on one particular player
    - [x] Handle simultaneous players playing
    - [x] Handle one player playing
  - [x] implement simultaneous pass
- [x] Test code 
- [x]  push to master branch

# Assignees 
@davidjha @aphelps4 @irobert4 
.

**Comment by aphelps4** [comment]
So to accomplish simultaneous passing, I was thinking that agent_turn() will be in charge of returning a list of agents. With hearts, the list would mostly be one agent but for the passing turn, it would return a list of all the agents (technically their number since the adjudicator does not have access to the agents). This brings up the question of how the adjudicator could figure out that it is a passing turn using the state and no other information. I was thinking it could check to see if there were no numbers greater than 1-4 in order to show that it is the beginning of the game. But if we had the players just pass their cards, we would still have a list of numbers 1-4 and the adjudicator would be stuck thinking that it is time for the players to pass their cards. In order to work around this issue, I was thinking that when we change the state to have the players pass their card, we also change the 2 of clubs to be played right away so that the game can infer that passing is over by using only the information found in the state.

**Comment by c-to-the-fazzy** [comment]
I think you are correct, `agent_turn()` will return a list of agents, together with their masked states.  

I think to accomplish the goal of determining when it's a passing round, there should be a data member on the state, similar to what is storing the trick leader.  This data member will also help track whether it's passing across, left, right, etc.

**Comment by aphelps4** [comment]
So if we use pass_type to keep track of what type of passing we are doing and whether or not we are passing, should we use 1-4 for the types of passing and make them negative when we are not passing?

**Comment by c-to-the-fazzy** [comment]
An encoding like
0 = not a pass round
1 = pass left
2 = pass right
3 = pass across
seems like it would make sense.

**Comment by aphelps4** [comment]
Ok, that makes sense. I thought you meant to know when it is a turn to pass at the beginning of the game but you are talking about the round where we do not pass.

**Comment by irobert4** [comment]
So for the list of players, should we only have a list of all four players for just the passing or is it for the entire round?

So the adjudicator is given four players for passing, then another four for trick one, then another four for trick two, and so on.

**Comment by c-to-the-fazzy** [comment]
Here's how I am thinking about it right now:

The general pattern is that updates to the state are alternated with player actions.  When players are playing tricks, the state is changing after each one of them plays a card.  So that implies to me that a trick should be a sequence of 4 different actions and resulting states.  Additionally, players that follow trick leader will naturally make their decision based on the cards played prior.  That additionally implies to me that the trick should be handled as 4 different actions in sequence; we need to update and mask the state after each player plays their card, before querying the next player for their actions.  

This is in contrast to the passing round, wherein players make their choice of what to pass *simultaneously* with the other players making the same decision.  Then, the pass is made, the state is updated (once), and play proceeds.  

So to answer your question, I think the pass uses all the agents simultaneously while the regular trick play uses 1 agent at a time.  

Does that seem right?

**Comment by aphelps4** [comment]
If we only want the state to update once for a simultaneous pass, that means we would prefer to give a list of the actions to step_game so that every change is handled at once rather than iterating through the list in base.py with a for loop calling step_game for each action right?

**Comment by c-to-the-fazzy** [comment]
Angela, that seems right to me.  

When the adjudicator does `step_game`, it should take the action(s) of the player(s) whose turn it is and produce a resultant state.
