### ISSUE TITLE
Edit-Adjudicator-To-Use-Trick-Leader-Encoding

### ISSUE THREAD

**Issue by irobert4** [c-to-the-fazzy/cardiathena#40]
# Description

We have decided to use an additional encoding of 31 - 34 in the state to represent the Trick Leader. The state.py file needs to have the encoding added, and the adjudicator needs to be updated to use the encoding.

# Tasks

- [x] Add the encoding to state.py
- [x]  In end_of_trick(): Where trick_winner is being set, update the state with the encoding instead.
- [x] Ensure that setting 21-24 and 31-34 properly sets to 11-14
- [x] Merge with papa branch
