### ISSUE TITLE
Isabellas-Cleanup-Branch-Review

### ISSUE THREAD

**Issue by irobert4** [c-to-the-fazzy/cardiathena#42]
# Description

A branch was created which contains the code for the current_player, lead_suit, and cards_of_trick along with a list of TODOs.  This branch should be reviewed by the team in person on Monday.

# Tasks

- [x] Review new inferring functions with team
- [x] Review TODOs with Team
- [x] Discuss how to wrap in new functions with existing step_game/agent_turn/other functions which need to use these functions with team.
- [x] Create a pull request and merge.

# Assignees 

David
Angela
Michael
Isabella

# Milestones

Review held on Monday (1/27/20).
