### ISSUE TITLE
couple/all of the inferring function integrations

### ISSUE THREAD

**Issue by msomarri** [c-to-the-fazzy/cardiathena#50]
# Description

Clean up the code by removing the global variables and replacing them with our functions. This is pretty much isabella slack post but opened up as an issue

# Tasks

- [x] **Integrate Trick_number** 
  - [x] Line 147
  - [x] Line149
   - [x] Line 265
   - [x] Line 296

- [x] **lead_suit**
  - [x] Line 149
  - [x]  Line 184-185
  - [ ] Line 403/416
  - [ ] Line 433
      - [x] replace with a call to (trick_number%13) > 1 and self.lead_suit() is None
   - [ ] Line  461/463

- [x] **cards_of_trick**
     - [x] Edit Function to handle the the return value. Currently return np.where **Goal** Return the actually Value 
     - [x] Line 154 
     - [x]  Line 269
     - [x] Line 281
     - [x] Line 285 
     - [x] Line  388
     - [x] Line 390

 - [x] **current_player** 
      - [ ] Line 158
       - [ ] Transform **encode_state.current_player**  to the inferring function.

 - [ ] **Testing**
    - [ ] Comment out Global Variable 
    - [ ] Run code to make sure it doesnt break 
    - [ ] Remove Global Variable
    - [ ] Check function that is completed   
# Assignees 
@msomarri 
ed.

**Comment by msomarri** [comment]
Closing this issue since most of it is complete. Will open a new issue for the current player
