### ISSUE TITLE
game manager: save_game() redux

### ISSUE THREAD

**Issue by davidjha** [c-to-the-fazzy/cardiathena#57]
# Description

The game manager's Save_game() method, in base.py, is currently saving an entire game's history as one entry in the database instead of having each state saved as its own entry.  

# Tasks

- [x] Re-implement save_game()
  - [x] Break up entire game state history into individual states.
  - [x] Implement any necessary changes for insertion/retrieval to/from database.

- [x] Add game tracking 
  - [x] Use uuid to link states to individual games.

**Comment by davidjha** [comment]
Changes/Additions have been pushed to mysql-on-argo branch.
