### ISSUE TITLE
Stateless-Adjudicator-Task

### ISSUE THREAD

**Issue by irobert4** [c-to-the-fazzy/cardiathena#59]
# Description

The Adjudicator and Game Manager need to be edited in order to make the Adjudicator stateless. All current references to the Adjudicator's State variable need to be replaced with the Game Manager's State variable.

# Tasks

- [x] Edit GameManager's constructor to initialize the State variable in place of the call to start_game().
- [x] Edit the Adjudicator:
  - [x] Add a parameter for the State from the Game Manager to step_game() and replace all references to self.state.
  - [x] Add a parameter for the State from the Game Manager to agent_turn(), and replace all references to self.state.
  - [x] Add a parameter for the State from the Game Manager to is_finished() and replace all references to self.state.
  - [x] Add a parameter for the State from the Game Manager to the various helper functions, replace all references.
- [x] Merge to master.

# Assignees 

@irobert4 

# milestones

Stateless Adjudicator
