### ISSUE TITLE
Database container on Argo

### ISSUE THREAD

**Issue by davidjha** [c-to-the-fazzy/cardiathena#6]
# Description

Test Argo for data collection to a SQL database. 

# Tasks

- [x] Run database locally in Singularity container
  - [x] Test a database in Docker container 
  - [x] Check ability to connect to database
  - [x] Create database, tables, and insert data
- [x] Teach group how to access Argo and run programs on it - 29 Nov. 2019
- [x] Teach group about singularity containers - 29 Nov. 2019
- [x] Run database in Singularity container on Argo
  - [x] Check ability to connect to database
  - [x] Create database, tables, and insert data

# Assignees 
@davidjha 

# Milestones
- Database way forward

# Dates

**11/29/2019** Argo class with Team W

I'm been trying to get PostgreSQL working in a singularity container. I'm able to get an instance running, but unable to connect from outside the container (on the same machine).  
Here are some issues and potential issues:
- Permission issues which were mostly write permissions. I've been able to get around some of these without the use of root. 
- Connecting locally to the running instance (on my laptop) needs work, and connecting within nodes on Argo is probably going to have to be approached differently.

For postgresql on docker, I was able to create a database in a container.  Although I didn't spend as much time on this as I have with singularity.

Argo has HDF preinstalled which is tailored for the storage of arrays (datasets). I can write up how this can be used to store our game states. I was able to create a hdf5 file and store a dataset. This may be another option.

This is just me trying to figure out what is feasible with the data collection on Argo.

- instantiate and communicate PostgreSQL container on singularity

- provide recommendation on suitability of ARGO environment for our project

**Comment by kruzaavn** [comment]
@davidjha with respect to your issue connecting to the  singularity container did you explicitly expose a port to connect to the container? Usually this is something that you need to do as part of your setup. Can you provide a link to your config file?

for docker configuration here is a [link](https://hub.docker.com/_/postgres) to the docker hub Postgres age with a lot of good information on how to configure a docker Postgres container. 

Pay close attention to the environment variables, and configuration files. Those are what you're going to want to setup so that you can interact with the container as a user other than as the root user. which is

**Comment by davidjha** [comment]
@kruzaavn 

> @davidjha with respect to your issue connecting to the singularity container did you explicitly expose a port to connect to the container? Usually this is something that you need to do as part of your setup. Can you provide a link to your config file?

I was able to track down how port mapping is done in singularity, and its slightly different then the way its done in docker. I didn't make a configuration file during my testing. I will need to do this in the future if everything works out. 

> for docker configuration here is a link to the docker hub Postgres age with a lot of good information on how to configure a docker Postgres container.

I appreciate the link to the postgres docker hub page, I've looked through it. However I ended up switching to mysql, and have made more progress with the switch. The docker hub page for mysql was helpful as well.

> Pay close attention to the environment variables, and configuration files. Those are what you're going to want to setup so that you can interact with the container as a user other than as the root user. which is

I was able to set up a non root account locally. I need to see how this is going to work on Argo. It shouldn't be an issue if accounts are preconfigured with root locally first, and then ran on Argo.

Here's what I was able to run on Argo. Current issue is connection to the mysql database from a python script.

`singularity instance start -e -c -home /scratch/dha5/home/ --bind /scratch/dha5/db/:/var/lib/mysql --bind /scratch/dha5/daemon/:var/run/mysqld --net --network-args "portmap=localhost:8888/tcp" mysql_test.simg athenasql`

-home : command defines a new home location. Finding the solution to this caused major cause of delays because the home directory isn't writeable from a compute node.

--bind : rebinds locations within the container to the host filesystem.

--net --network-args : maps ports.

**Comment by davidjha** [comment]
Here's a configuration file I found on singularity hub and a helpful resource.

[https://github.com/c-to-the-fazzy/cardiathena/blob/mysql-on-argo/argo/Singularity.latest](url)

[https://www.hpc.iastate.edu/guides/containers/mysql-server](url)

Here are the steps I've taken to run this on Argo. 

Starts the instance from the container
singularity instance start -e -c --bind ${PWD}/mysql/var/lib/mysql/:/var/lib/mysql --bind ${PWD}/mysql/run/mysqld:/run/mysqld mysql.simg mysql

Runs the start script inside the container
singularity run instance://mysql

In a second terminal, I can shell into the container and run mysql. From there I can create a user, and grant privileges to the new users. I can also create db, tables, and etc..

The problem is I can do this from the head nodes (login node) of Argo, but these are not meant to run long running or intensive jobs. 

I pass this job onto the slurm scheduler, and it seems once it runs :

`singularity instance start -e -c --bind ${PWD}/mysql/var/lib/mysql/:/var/lib/mysql --bind ${PWD}/mysql/run/mysqld:/run/mysqld mysql.simg mysql`

Then it seems like the process gets killed and runs the next command:

`singularity run instance://mysql`

This results in an error message, instance mysql not found.

My Slurm script attached.
[https://github.com/c-to-the-fazzy/cardiathena/blob/mysql-on-argo/argo/slurm_script.slurm](url)

I've set up to meet with an Argo admin on Wednesday.

**Comment by c-to-the-fazzy** [comment]
Ok I get the problem: so when you do `singularity instance start` and `singularity run instance`, those are commands issued by you while you're logged into the head nod, which is not an Argo intended use pattern.  However, when you schedule those commands via slurm (which IS an Argo intended use pattern), they seem to lack some persistence.  

I hope/expect the Argo admin will have a recipe or solution template on hand.  I basically think it's impossible that we're the first group who has wanted to have a containerized DB service running for other jobs to connect to.  

David, if you have any questions come up live during the meeting you can always ping the team on slack from your phone.  We can't promise we'll be online at that time, but it could always be worth a shot.

**Comment by davidjha** [comment]
So Jeff showed me how to run stuff directly on a compute node, and we're able to sort identify what might be causing the issue.  

2019-12-04T23:25:58.489033Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2019-12-04T23:25:58.489075Z 0 [Note] IPv6 is available.
2019-12-04T23:25:58.489086Z 0 [Note]   - '::' resolves to '::';
2019-12-04T23:25:58.489106Z 0 [Note] Server socket created on IP: '::'.
2019-12-04T23:25:58.519736Z 0 [ERROR] Another process with pid 52 is using unix socket file.
2019-12-04T23:25:58.519747Z 0 [ERROR] Unable to setup unix socket lock file.
2019-12-04T23:25:58.519750Z 0 [ERROR] Aborting

Then the container proceeds to shutdown, which is why a container instance can't be found. 

`singularity instance start -e -c --bind ${PWD}/mysql/var/lib/mysql/:/var/lib/mysql --bind ${PWD}/mysql/run/mysqld:/run/mysqld --network-args "portmap=6603:3306/tcp" mysql.simg mysql`

The port map arguments aren't actually changing the ports from the line above. We're going need to change the default port that mysql uses, which I think can be done in my.cnf config file. This requires rebuilding the image file, which I'll be able to get to later this week. 

Another step taken includes disabling IPv6 (work in progress because need to rebuild container image to do this) at the request of the IT guy, Chris. Chris is also going to investigate further, and we should be able to solve this. He says this is doable, and we're not the first group to attempt this for sure.

**Comment by davidjha** [comment]
I ended up running salloc, which allocates a node in real time, and ran the mysql container on that. I was able to submit a regular job with my python script to connect to the database. I was able to insert data, and query it. 

So I think this issue can be closed.
