### ISSUE TITLE
Database of players

### ISSUE THREAD

**Issue by davidjha** [c-to-the-fazzy/cardiathena#62]
# Description

When the implementation of the minimizing agent is completed, cardiathena will have 2 agent types. A database of the players that participated in a game could be used for tracking purposes. 

# Tasks

- [x] Implement database of players
  - [x] Design database to incorporate this
  - [x] Documentation for players database
  - [ ] Code implementation
      - [ ] Code retrieval of agents list from database

**Comment by davidjha** [comment]
Closing due to new schema from Issue#68.
