### ISSUE TITLE
The Low-Layer ( Minimizing Agent )

### ISSUE THREAD

**Issue by msomarri** [c-to-the-fazzy/cardiathena#64]
# Description
The low-layer plays defensively, and wants to minimize point

# Tasks

**Helping Functions**
- [x] Implement is_lead(partial_state) to check if player is leading
- [x] Implement not_void(partial_state) to check whether the player is void in the leading suit or not

**Passing**
- [x] **Method 1**: Pass highest cards in trouble suits: suits where the lowest card is higher than any other lowest card in other suits. If the player becomes void, then pass off the next high cards from the next trouble suit.
- [x]  **Method 2:** Average the face cards in each suit, and pass the highest cards from the suit with the highest average. (J = 11, Q = 12, K = 13, A = 14). Repeat if void.

**Leading**
Boolean Functions
- [x]  not holding the QS and not in spades trouble (not holding KS or AS or has enough low spades to cover for the KS or AS). Lead with any spades to draw out the QS.
- [x] Has no spades or the QS has been played, lead with the lowest card of any suit. Or lead with the suit that has been played the least.

**Normal Plays**
- [x] Play the highest card that is under the highest card on the table. Otherwise, if the player is the last to play, then play the safest high card.

**Void Play** 
 - [x] pick the highest card from a trouble suit.

**Comment by aphelps4** [comment]
We should discuss consolidating MinimizingAgent.py and MinimizingAgentV2.py into one file. It seems like V2 has the player call the sloughing function when they are void in the suit while V1 makes a random choice there. V1 has more changes so I believe it would be easier to move the functions sloughing(partial_state) (lines 120-131) and bad_suit() (lines 133-154) from V2 to V1 and change line 84 of V1 to line 77 of V2.
@msomarri @irobert4 Does that sound good to you guys?

**Comment by irobert4** [comment]
I agree with this, I think we should also consider renaming the Minimizing Agent to something else.  On slack, Carlo suggested "BasicAgent" or "TrickAvoidingAgent", but we could also go with "LowLayerAgent".
