### ISSUE TITLE
Database schema revamp

### ISSUE THREAD

**Issue by davidjha** [c-to-the-fazzy/cardiathena#68]
# Description
From the meeting on the 21st, Carlo, Aleks and I went over the database schema. 
The current database schema could be adjusted to include additional information. New information about the games include a timestamp and agent version number. Other modifications to the schema can include a new game table. The game table tracks the game id, timestamp, and the four agents as foreign keys. The four agents reference an entry in the agent_id in agent's table. 

Could there be any additional agent metadata other than the version number? Maybe number of wins?

Current Schema:
![image](https://raw.githubusercontent.com/c-to-the-fazzy/cardiathena/mysql-on-argo/documentation/img/cardiathena_eer_diagram.png)
New Schema:
![image](https://raw.githubusercontent.com/c-to-the-fazzy/cardiathena/mysql-on-argo/documentation/img/DbSchemav2.png)

# Tasks

- [x] Code up changes in mysql-on-argo-new-schema branch
  - [x] Agent Table
      - [x] create table in initialize_table() from MySQLDatabase.py
      - [x] Insertion function 
  - [x] State Table
      - [x] create table in initialize_table() from MySQLDatabase.py
      - [x] Insertion function 
  - [x] Game Table
      - [x] create table in initialize_table() from MySQLDatabase.py
      - [x] Insertion function 
- [x] Add additional game information if needed.

**Comment by davidjha** [comment]
I decided to get rid of initialize_table() and import per-configured tables via a .sql file. I think this has simplified the code quite a bit. The .sql file has been pushed into the database/MySQL folder as cardiathena.sql. 

A game_uuid entry has been added as a foreign key in place of game_id in the state table referencing a new entry game_uuid in the game table. I couldn't think of any way of getting the game_id from the state table to reference the game_id in the game table, since its auto-incremented by the MySQL server itself. I could query a id but it would be hard to tell if the states actually belong to that game.
