### ISSUE TITLE
Hearts_Agent Abstract Class

### ISSUE THREAD

**Issue by msomarri** [c-to-the-fazzy/cardiathena#69]
# Description

It would be nice to have an abstract class for the Hearts agent to include functions that would make it easy to build model agents and eventually learning agents. 

# Tasks

- [x] Create Hearts_Agent.py and added to the Agent folder
  - [ ] Add base functions . Here are some suggestions. Please add more 
     - [ ] **Sort_Suit**: Help organize the cards by the suits that they belong to.  
     - [ ] **Select_card:** Chooses a card to lead with 
     - [ ] **Average_facecards**: Calculate the average of a suit depending on the card's face values. 
     - [ ] **Has_queen_been_played** : Boolean to check if the queen has been played
     - [ ] **Save_Game**: Saves training data for potential learning agents. Haven't thought about the 
           training data to much but i think we should structure the data in the following matter. i 
           would like any help or suggestion on this.
          **Agent Type** |  **Trick #1 - trick #13** | **Points_gained** | **Possible Trick Plays #1 - #13**
     - [ ] **void_suit():** Checks to see if the agent is void or not in particuler suit 
- [ ] Test code 
   - [ ] build a quick prototype with the abstract class 
   - [ ] have it play against other agents

**Comment by irobert4** [comment]
Should we have a "void_suit()" function as well to check if an agent is void in a particular suit?

These other functions look like good additions.

**Comment by davidjha** [comment]
That would probably make sense, since many different types of agents might want to know if its void in a suit.

**Comment by aphelps4** [comment]
We will also probably want our agents to know when another agent is void in a suit. AKA agent 1 notices agent 2 was void in a suit that trick and stores that information for future plays.
