### ISSUE TITLE
Wiki clean up

### ISSUE THREAD

**Issue by davidjha** [c-to-the-fazzy/cardiathena#71]
# Description

From our meeting discussions, the wiki contains game specific information that should be moved.

# Tasks

- [x] Move hearts specific stuff to readme files in their directories.
  - [x] Agents Class Design
  - [x] Database Design Document
  - [x] Distributed Computing Document
  - [x] Game Adjudicator Class Design Document
  - [x] Game Manager Design Document
  - [x] General Hearts Strategies
  - [x] Hearts Action
  - [x] Hearts State
  - [x] Minimizing Agent

We might want to possibly restructure the directories for the derived classes, and hearts specific files.

**Comment by davidjha** [comment]
Removed General Hearts Strategies. Refer to Mark's page to reference these strategies. Removed hearts/mysql specific information off the wiki page for database design document. The readme files have been updated/added in the mysql-on-argo branch database directory. 

Removed Distributed Computing Document from the wiki. I'm not sure how to keep this general. I can add back in if needed. The information contained in that directory has been moved to a readme.md.

**Comment by davidjha** [comment]
All the tasks are complete, closing.
