### ISSUE TITLE
Clean Up State.py

### ISSUE THREAD

**Issue by aphelps4** [c-to-the-fazzy/cardiathena#75]
# Description

Our state.py file still has a lot of useless bloat in it. We should get rid of everything we do not need along with fixing values to deck.

# Tasks

- [x] change values to deck
- [x] remove unused variables
- [x] remove unused functions
