### ISSUE TITLE
The Equalizer Agent

### ISSUE THREAD

**Issue by irobert4** [c-to-the-fazzy/cardiathena#77]
# Description

This agent focuses primarily on inflicting points onto other players.

# Tasks

**Passing**

- [x] This agent wants to hoard its spades (including the Queen) and hearts, but wants to try and void out its Diamonds and Clubs. The agent should pick whichever suit has the most problem cards and pass them to the other player.

**Leading**

- [x] This agent will lead with a card from its shortest suit (may want to have it prefer leading with either Clubs or Diamonds).
  - Should this agent focus on leading with high cards to start, and then switch over to low cards?

**Following**

- [x] To start with the agent should probably focus on voiding Clubs and Diamonds.
- [x] Once the suits have been voided, this agent could start playing Hearts cards.
  - [x] High hearts cards may need an additional strategy. (thoughts?)
- [x] The Queen should be played when this Agent cannot follow suit, or when the King/Ace of Spades has been played in the same trick. (thoughts?)
