### ISSUE TITLE
The Shooter Agent

### ISSUE THREAD

**Issue by irobert4** [c-to-the-fazzy/cardiathena#78]
# Description

This agent shoots for the moon, it aims to take all of the points cards.

# Tasks

**Passing**

- [x] This agent wants to pass its low cards, particularly it's low Hearts cards.
  - If this agent was up against an intelligent agent, this strategy could immediately backfire on it.  (thoughts?)

**Leading**

- [x] Early game leading: The agent will lead with a low card. (from a long suit or short one? Which suit type?)
- [x] Late game leading: The agent will (probably) lead with a high card.

**Following**

- [x] Early game following: The agent doesn't want to win tricks with no points in them, and it doesn't want to expend all of its high cards, so it should play low cards and hope no other agent breaks Hearts.
- [x] Late game following: Hearts are probably being played by this point, so this agent will want to play its higher cards.

**Some notes**

- If the agent holds the queen, it will most likely want to try and take all of the Hearts before playing the Queen.
- There doesn't seem to be much of a focus on voiding your own suits.
- The best hand for this Agent appears to be the Jack, Queen, King, and Ace of Hearts, plus the Queen.

**Comment by c-to-the-fazzy** [comment]
My advice would be to implement this agent as-is; namely, that it *always* tries to shoot the moon.  This strategy will likely suck overall, but may occasionally produce excellent rounds.  In that case, you'll have verified that it works (none of the other agents likely have any chance of shooting the moon by accident, ever).  

Isabella, your observation that it could backfire against an intelligent agent is OK.  Once it's verified that this agent works, you can look into hybridizing it with other strategies.  For example, an agent that plays like the LowLayer, but if it gets the first heart then it switches to ShootTheMoon.  

Focusing development effort onto an isolated/encapsulated STM strategy before moving on to a more nuanced strategy seems like a good approach to me.  Just my $0.02...
