### ISSUE TITLE
Database Cloud Services

### ISSUE THREAD

**Issue by irobert4** [c-to-the-fazzy/cardiathena#8]
# Description

Need to research which cloud computing service would best fit our needs.

Current ideas/Alternatives to storage on Argo: Azure, AWS, GCE, etc.

What are we leaning towards: Azure (Microsoft provides a 250GB SQL database and 12 months of free services).

We were considering MongoDB’s Atlas but it was deemed to be too slow and limited in storage to be acceptable.

# Tasks

- [ ] Create accounts for one or more of these services
  - [ ] Research limits (ex, Azure has a 250GB limit, AWS has less) and pick one of these alternatives
  - [ ] Produce a sql server prototype.
- [ ] Configuration file.
- [ ] Need to try and get Argo to communicate with the prototype.

# Dates

**12/2/2019** Research (maybe the Prototype too, if it's easy) should be done.

**Comment by irobert4** [comment]
**12/4/2019** Created an account on Microsoft's Azure, tested Azure's Batch Services
 - Created a pool with two cores in it, ran a sample task on it. (Followed the QuickStart guide for Azure portal).
 - Attempted to delete the pool.  Ran into some (now solved) admin issues.

**Comment by msomarri** [comment]
Closing this Issue for now since we have moved on to using Argo
