### ISSUE TITLE
Selecting agents randomly from available agents

### ISSUE THREAD

**Issue by aphelps4** [c-to-the-fazzy/cardiathena#87]
# Description

One of the goals for this month is to implement a feature in play_hearts.py where the types of agents are randomly chosen from what is currently available for the four players of the game. There are two different ways I think we can do this. The first is that we could see if python allows us to turn strings into functions. The next option (which I believe is the more likely choice) is that we could have our agents capable of making clones so that we can have a list of each agent type that will make a clone whenever it gets chosen to represent a player. If anyone comes up with other options, feel free to provide your ideas.

# Tasks

- [x] Choose a strategy to accomplish our goal
  - [x] Provide any new ideas if available
  - [x] Determine the most feasible option
- [x] Implement get_agent function that works
- [x] Update get_agent function to use strings

**Comment by irobert4** [comment]
Why exactly do the agents need to make clones? 

I was thinking that to start we could just have a function that returns an agent based on a number randomly generated from 0-3 and just add that function call to agent_1, agent_2, etc. in play_hearts.py.
