### ISSUE TITLE
Finish Learning Agent Documentation

### ISSUE THREAD

**Issue by aphelps4** [c-to-the-fazzy/cardiathena#9]
# Description

Finish the documentation of the learning agent by posting research and creating pseudo-code. Base Agent should be done before working on this agent.

# Tasks

- [x] post link to sklearn decision tree
  - [ ] figure out legality of using their code
- [ ] decide on features to use in decision tree
- [ ] create pseudo-code
